kind: Deployment
apiVersion: apps/v1
metadata:
  name: task-manager-rest-application
spec:
  selector:
    matchLabels:
      app: task-manager-rest-application
      name: task-manager-rest-application
  replicas: 1
  template:
    metadata:
      labels:
        app: task-manager-rest-application
        name: task-manager-rest-application
    spec:
      containers:
        - name: task-manager-rest-application
          image: bom.ocir.io/bmkvfx57mojv/task-manager-rest-app:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: task-manager-secret