kind: Service
apiVersion: v1
metadata:
  name: task-manager-rest-application
  namespace: default
spec:
  selector:
    app: task-manager-rest-application
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080